import { describe, expect, it } from 'vitest';
// Written by Gobl's TypeScript generator (`make generate`); importing the bundle registers the entities.
import { Membership, Role, Status, User } from './generated/gobl/index.ts';
import { GOBL_ENTITY_MARKER, parseGoblJSON, toInstance } from '../../src/index.ts';

describe('entities generated by Gobl', () => {
	it('read and write their columns through the generated accessors', () => {
		const u = new User({ user_id: '1', user_name: 'Ada', user_status: Status.ACTIVE });

		expect(u.name).toBe('Ada');
		u.status = Status.BLOCKED;
		expect(u.toObject(true)).toEqual({ user_status: 'blocked' });
	});

	it('give the single primary key of a saved entity, and refuse it for an unsaved one', () => {
		expect(new User({ user_id: '7' }).singlePKValue()).toBe('7');
		expect(() => new User().singlePKValue()).toThrow('Cannot get single PK value for unsaved "User".');
	});

	it('are revived from JSON by their marker', () => {
		const payload = JSON.stringify({
			user: new User({ user_id: '1', user_name: 'Ada' }),
			roles: [new Role({ role_id: '2', role_title: 'admin', role_user_id: '1' })],
		});
		const parsed = parseGoblJSON(payload);

		expect(parsed.user).toBeInstanceOf(User);
		expect(parsed.roles[0]).toBeInstanceOf(Role);
		expect(parsed.roles[0].title).toBe('admin');
	});

	it('are recognized from their columns when the API sends no marker', () => {
		const e = toInstance({ membership_group: 1, membership_member: 2, membership_label: null });

		expect(e).toBeInstanceOf(Membership);
		expect((e as Membership).member).toBe(2);
	});

	it('are found in the cache by their string key once cached', () => {
		const cached = toInstance({ [GOBL_ENTITY_MARKER]: 'User', user_id: '42', user_name: 'Grace' }, true);

		expect(User.fromCache('42')).toBe(cached);
	});

	it('use a complete composite primary key as cache key', () => {
		expect(new Membership({ membership_group: 3, membership_member: 4 }).cacheKey()).toBe('["3","4"]');
		expect(new Membership({ membership_group: 3 }).cacheKey()).toBeNull();
	});

	it('are found in the cache by the string of a numeric key', () => {
		const cached = toInstance({ [GOBL_ENTITY_MARKER]: 'User', user_id: 43 }, true);

		expect(User.fromCache('43')).toBe(cached);
	});
});
